# Generated by Django 3.0.5 on 2020-11-14 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_auto_20201106_1317'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='items',
            options={},
        ),
        migrations.DeleteModel(
            name='Content',
        ),
    ]
