# Generated by Django 3.1.3 on 2020-11-17 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0006_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='itemid',
            field=models.CharField(max_length=200),
        ),
    ]
