# Generated by Django 3.1.3 on 2020-11-27 10:08

import Products.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0007_auto_20201117_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='Med_file',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=200)),
                ('mediafile', models.FileField(storage=Products.storage.OverwriteStorage(), upload_to='')),
            ],
        ),
    ]
