# Generated by Django 3.1.3 on 2020-12-02 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0008_med_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='specs',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
